apiVersion: v1
kind: Service
metadata:
  name: mozart-elasticsearch
  labels:
    component: mozart
    run: mozart-elasticsearch
spec:
  type: NodePort
  ports:
  - port: 9200
    protocol: TCP
    name: http
  - port: 9300
    protocol: TCP
    name: tcp
  selector:
    component: mozart
    run: mozart-elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mozart-elasticsearch
  labels:
    component: mozart
    run: mozart-elasticsearch
spec:
  selector:
    matchLabels:
      component: mozart
      run: mozart-elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        component: mozart
        run: mozart-elasticsearch
    spec:
      containers:
      - name: mozart-elasticsearch
        image: hysds/elasticsearch:latest
        command: [ "elasticsearch" ]
        args: [ "-Des.node.name='mozart-elasticsearch'",
                "-Des.cluster.name='resource_cluster'",
                "-Des.bootstrap.mlockall=true",
                "-Des.network.host=0" ]
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: tcp
        resources:
          limits:
            cpu: "0.5"
        env:
        - name: ES_HEAP_SIZE
          value: "100m"
        - name: MAX_LOCKED_MEMORY
          value: "unlimited"
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
        - mountPath: /usr/share/elasticsearch/config
          name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          emptyDir: {}
