apiVersion: v1
kind: Service
metadata:
  name: mozart-redis
  labels:
    component: mozart
    run: mozart-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    component: mozart
    run: mozart-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mozart-redis
  labels:
    component: mozart
    run: mozart-redis
spec:
  selector:
    matchLabels:
      component: mozart
      run: mozart-redis
  replicas: 1
  template:
    metadata:
      labels:
        component: mozart
        run: mozart-redis
    spec:
      containers:
      - name: mozart-redis
        image: hysds/redis:latest
        command: [ "redis-server" ]
        args: [ "/redis-master/redis.conf" ]
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "1.0"
        volumeMounts:
        - mountPath: /data/redis
          name: data
        - mountPath: /redis-master
          name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: hysds-mozart-config
            items:
            - key: redis-config
              path: redis.conf
