apiVersion: v1
kind: Service
metadata:
  name: mozart-rabbitmq
  labels:
    component: mozart
    run: mozart-rabbitmq
spec:
  type: NodePort
  ports:
  - port: 5672
    protocol: TCP
    name: amqp
  - port: 15672
    protocol: TCP
    name: http
  selector:
    component: mozart
    run: mozart-rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mozart-rabbitmq
  labels:
    component: mozart
    run: mozart-rabbitmq
spec:
  selector:
    matchLabels:
      component: mozart
      run: mozart-rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        component: mozart
        run: mozart-rabbitmq
    spec:
      containers:
      - name: mozart-rabbitmq
        image: hysds/rabbitmq:latest
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: http
        resources:
          limits:
            cpu: "1.0"
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: data
        - mountPath: /etc/rabbitmq/rabbitmq.config
          name: config
          subPath: rabbitmq.config
        - mountPath: /etc/default/rabbitmq-server
          name: config
          subPath: rabbitmq-server
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: hysds-mozart-config
