apiVersion: v1
kind: Service
metadata:
  name: grq-elasticsearch
  labels:
    component: grq
    run: grq-elasticsearch
spec:
  type: NodePort
  ports:
  - port: 9200
    protocol: TCP
    name: http
  - port: 9300
    protocol: TCP
    name: tcp
  selector:
    component: grq
    run: grq-elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grq-elasticsearch
  labels:
    component: grq
    run: grq-elasticsearch
spec:
  selector:
    matchLabels:
      component: grq
      run: grq-elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        component: grq
        run: grq-elasticsearch
    spec:
      initContainers:
        - name: init-grq-data
          image: alpine/git
          resources:
            requests:
              ephemeral-storage: "8Gi"
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: data
          - mountPath: /wait-for-it.sh
            name: global-config
            subPath: wait-for-it.sh
          command: ['sh', '-c', 'if [ ! -d "/usr/share/elasticsearch/data/products_cluster" ]; then git clone https://github.com/hysds/puppet-grq.git; cat puppet-grq/files/elasticsearch-data.tbz2.* > elasticsearch-data.tbz2; tar xjvf elasticsearch-data.tbz2; mv elasticsearch/products_cluster /usr/share/elasticsearch/data/; fi;']
      containers:
      - name: grq-elasticsearch
        image: hysds/elasticsearch:latest
        command: [ "elasticsearch" ]
        args: [ "-Des.node.name='grq-elasticsearch'",
                "-Des.cluster.name='products_cluster'",
                "-Des.bootstrap.mlockall=true",
                "-Des.network.host=0" ]
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: tcp
        resources:
          limits:
            cpu: "1.0"
        env:
        - name: ES_HEAP_SIZE
          value: "1g"
        - name: MAX_LOCKED_MEMORY
          value: "unlimited"
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
        - mountPath: /usr/share/elasticsearch/config
          name: config
      volumes:
        - name: global-config
          configMap:
            name: hysds-global-config
        - name: data
          persistentVolumeClaim:
            claimName: grq-elasticsearch-pvc
        - name: config
          emptyDir: {}
      nodeSelector:
        beta.kubernetes.io/instance-type: "3"
