apiVersion: v1
kind: Service
metadata:
  name: ci
  labels:
    component: ci
    run: ci
spec:
  type: NodePort
  ports:
  - port: 22
    protocol: TCP
    name: ssh
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  - port: 8080
    protocol: TCP
    name: jenkins
  - port: 8085
    protocol: TCP
    name: dav
  - port: 9001
    protocol: TCP
    name: supervisord
  selector:
    component: ci
    run: ci
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci
  labels:
    component: ci
    run: ci
spec:
  selector:
    matchLabels:
      component: ci
      run: ci
  replicas: 1
  template:
    metadata:
      labels:
        component: ci
        run: ci
    spec:
      initContainers:
      - name: overwrite-container-builder
        image: alpine/git
        volumeMounts:
        - mountPath: /container-builder
          name: container-builder
        - mountPath: /container-met.py
          name: config
          subPath: container-met.py
        - mountPath: /overwrite-container-builder.sh
          name: config
          subPath: overwrite-container-builder.sh
        workingDir: /container-builder
        command: ['sh', '/overwrite-container-builder.sh']
      containers:
      - name: ci
        image: hysds/cont_int:latest
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 8080
          name: jenkins
        - containerPort: 8085
          name: dav
        - containerPort: 9001
          name: supervisord
        resources:
          limits:
            cpu: "1.0"
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersock
        - mountPath: /home/ops/.ssh/id_rsa
          name: global-secrets
          subPath: id_rsa
          readOnly: true
        - mountPath: /home/ops/.ssh/authorized_keys
          name: global-secrets
          subPath: id_rsa.pub
          readOnly: true
        - mountPath: /home/ops/.aws/config
          name: global-config
          subPath: aws_config
          readOnly: true
        - mountPath: /home/ops/.aws/credentials
          name: global-config
          subPath: aws_credentials
          readOnly: true
        - mountPath: /home/ops/verdi/etc/celeryconfig.py
          name: global-config
          subPath: celeryconfig.py
        - mountPath: /home/ops/verdi/etc/datasets.json
          name: global-config
          subPath: datasets.json
        - mountPath: /home/ops/verdi/ops/container-builder
          name: container-builder
        - mountPath: /home/ops/verdi/log
          name: log
        - mountPath: /data/work
          name: work
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: global-secrets
        secret:
          secretName: hysds-global-secrets
      - name: global-config
        configMap:
          name: hysds-global-config
      - name: config
        configMap:
          name: hysds-ci-config
      - name: log
        emptyDir: {}
      - name: work
        emptyDir: {}
      - name: container-builder
        emptyDir: {}
