apiVersion: v1
kind: Pod
metadata:
  name: metrics
spec:
  initContainers:
    - name: init-metrics-redis
      image: busybox
      volumeMounts:
      - mountPath: /wait-for-it.sh
        name: global-config
        subPath: wait-for-it.sh
      command: ['sh', '/wait-for-it.sh', '-t', '0', 'metrics-redis:6379']
    - name: init-metrics-elasticsearch
      image: busybox
      volumeMounts:
      - mountPath: /wait-for-it.sh
        name: global-config
        subPath: wait-for-it.sh
      command: ['sh', '/wait-for-it.sh', '-t', '0', 'metrics-elasticsearch:9200']
  containers:
  - name: metrics
    image: hysds/metrics:latest
    ports:
    - containerPort: 22
      name: ssh
    - containerPort: 80
      name: http
    - containerPort: 443
      name: https
    - containerPort: 5601
      name: kibana
    - containerPort: 9001
      name: supervisord
    resources:
      limits:
        cpu: "0.5"
    volumeMounts:
    - mountPath: /home/ops/.ssh/id_rsa
      name: global-secrets
      subPath: id_rsa
      readOnly: true
    - mountPath: /home/ops/.ssh/authorized_keys
      name: global-secrets
      subPath: id_rsa.pub
      readOnly: true
    - mountPath: /home/ops/.aws/config
      name: global-config
      subPath: aws_config
      readOnly: true
    - mountPath: /home/ops/.aws/credentials
      name: global-config
      subPath: aws_credentials
      readOnly: true
    - mountPath: /home/ops/metrics/etc/celeryconfig.py
      name: global-config
      subPath: celeryconfig.py
    - mountPath: /home/ops/metrics/etc/datasets.json
      name: global-config
      subPath: datasets.json
    - mountPath: /home/ops/metrics/etc/indexer.conf
      name: config
      subPath: indexer.conf
    - mountPath: /home/ops/metrics/log
      name: log
  volumes:
  - name: global-secrets
    secret:
      secretName: hysds-global-secrets
  - name: global-config
    configMap:
      name: hysds-global-config
  - name: config
    configMap:
      name: hysds-metrics-config
  - name: log
    emptyDir: {}
